### ISSUE TITLE
Question about recitation

### ISSUE THREAD

**Issue by ezvision** [0xzer0x/quran-companion#25]
Hey brother, first of all I just wanted to say I've been using your program a lot and really love it. Thank you for your work.

I just had a question regarding the recitations. I wanted to ask if you used any program to cut the surahs into individual verses. There's a reciter I've been listening to recently and I was wondering if it would be possible for me to add in his recitation myself if I could figure out how you did this.

Regards.

**Comment by 0xzer0x** [comment]
As-salamu alaykum,
I didn't cut the recitations myself rather I used projects that already did this work such as [EveryAyah](https://everyayah.com/recitations_ayat.html) and [AlQuranCloud](https://alquran.cloud/cdn).

But you can add your favorite reciter by converting his full surah recitations to verse mp3 files in the format *sssvvv.mp3* where **s** is the 0-padded surah number & **v** is the 0-padded verse number in the surah (002005.mp3 = surah 2 verse 5) , I would suggest using [Audacity](https://www.audacityteam.org/download/) for the whole process as it offers  *labels* feature for exporting segments of an audio file. Let us take an example so that the process becomes clear.

We want to export surah Al-Fatihah to separate mp3 files, so we start by downloading the surah recitation & opening it in Audacity.

1. Select the verse segment

![verse segment](https://i.ibb.co/CV5mktq/2023-09-27-10-22-55.png)

2. Add a label for the selected segment through `Edit -> Labels -> Add Label at Selection` or through <kbd>Ctrl</kbd> + <kbd>B</kbd> and name the label using the naming convention mentioned
![labeled segment](https://i.ibb.co/2qH3L96/2023-09-27-10-26-18.png)

3. Repeat steps 1-2 for the rest of the surah

4. Once done, export the labels in case you want to modify the timing of any verse or export the verses at a different bit rate. This can be done through `File -> Export -> Export Labels...` which will save it as a text file.

5. Export the actual verse mp3 files through `File -> Export -> Export Multiple...`, choose an output folder (I suggest a separate folder for each surah which contains the mp3s and the labels text file) and use the following options
  - Format: MP3 Files
  - Bit Rate Mode: Average
  - Quality: 64kbps
  - Channel Mode: Joint Stereo
  - Split files based on: Labels (don't include audio before first label)
  - Name files: Using Label/Track Name

After you have successfully exported the 114 surahs to mp3 files, you can create a [GitLab](https://gitlab.com/) account and fork [qc-audio](https://gitlab.com/0xzer0x/qc-audio) repository (you might need to install `git-lfs`), clone your fork locally, add all the recitation files into a single directory named using the following convention *name_bitrate*. The final step is to open a [merge request](https://docs.gitlab.com/ee/user/project/merge_requests/creating_merge_requests.html) to merge your fork with the main repository.

I hope this answer is sufficient inshallah. Feel free to contact me if you face any difficulties.

Thanks

**Comment by 0xzer0x** [comment]
I have opened the discussions tab, perhaps post there progress on the specific reciter you want to add and people interested in adding the same reciter can collaborate in order to reduce the individual burden.

**Comment by ezvision** [comment]
Thank you so much for giving me this information. The reciter is a bit obscure compared to others but I enjoyed his recitation and managed to find all of the surahs. I will go through this later and start doing it slowly when I have the time. I'll get back to you if I need to ask any questions.

Jazak Allah Khair
